name: train
run_id: commands[0]
env COMSPEC: C:\WINDOWS\system32\cmd.exe
env NUMBER_OF_PROCESSORS: 8
env PATHEXT: .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW;.CPL
env PROCESSOR_ARCHITECTURE: AMD64
env PROGRAMDATA: C:\ProgramData
env PROGRAMFILES: C:\Program Files
env PROGRAMFILES(X86): C:\Program Files (x86)
env SYSTEMDRIVE: C:
env SYSTEMROOT: C:\WINDOWS
env TEMP: C:\Users\yasht\AppData\Local\Temp
env TMP: C:\Users\yasht\AppData\Local\Temp
env USERPROFILE: C:\Users\yasht
env LANG: en_US.UTF-8
env PATH: C:\Users\yasht\Desktop\ML-ops\titaninc_assignment2\.tox\test_package\Scripts;C:\Python311\Scripts\;C:\Python311\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Users\yasht\AppData\Local\Programs\Python\Python310\Scripts\;C:\Users\yasht\AppData\Local\Programs\Python\Python310\;C:\Users\yasht\AppData\Local\Microsoft\WindowsApps;C:\Users\yasht\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\MongoDB\Server\6.0\bin;C:\Users\yasht\AppData\Roaming\npm
env PIP_DISABLE_PIP_VERSION_CHECK: 1
env PYTHONIOENCODING: utf-8
env PYTHONPATH: .
env PYTHONHASHSEED: 0
env TOX_ENV_NAME: train
env TOX_WORK_DIR: C:\Users\yasht\Desktop\ML-ops\titaninc_assignment2\.tox
env TOX_ENV_DIR: C:\Users\yasht\Desktop\ML-ops\titaninc_assignment2\.tox\test_package
env VIRTUAL_ENV: C:\Users\yasht\Desktop\ML-ops\titaninc_assignment2\.tox\test_package
env COLUMNS: 140
env LINES: 14
metadata pid: 220
cwd: C:\Users\yasht\Desktop\ML-ops\titaninc_assignment2
allow: C:\Users\yasht\Desktop\ML-ops\titaninc_assignment2\.tox\test_package\Scripts\*
cmd: python classification_model/train_pipeline.py
exit_code: 1

standard error:
Traceback (most recent call last):
  File "C:\Users\yasht\Desktop\ML-ops\titaninc_assignment2\classification_model\train_pipeline.py", line 1, in <module>
    from config.core import config
  File "C:\Users\yasht\Desktop\ML-ops\titaninc_assignment2\classification_model\config\core.py", line 4, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
